# -*- coding: utf-8 -*-
"""egeaktemur_the2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dIUlCmpleCzQKa8svrSM-lppB8rCxBUL
"""

#Ege Aktemur
curterm = (input("Please enter your current term: "))
if str(curterm).isalnum() == False or str(curterm).isdigit() ==False or int(curterm) <1 :
  print("Invalid input for the current term.")
elif str(curterm).isalnum() == True and str(curterm).isdigit() == True and int(curterm) < 2 :
  print("Your Erasmus score cannot be calculated before the 2nd term.")
else:
  credit = int(input("Please enter the total credits you earned before: "))
  if str(credit).isdigit() ==False:
    print("Invalid input for the credits earned before.")
  elif str(credit).isdigit() ==True and int(curterm) == 2 and credit <34 or int(curterm) == 3 and credit <49 or int(curterm) >3 and credit <58:
    print("Your Erasmus score cannot be calculated before you took the required amount of credits.")
  else:
    sps101b = input("Please enter the SPS101 letter grade equivalents: ")
    sps101 = sps101b.lower()
    if ";:" in sps101 or ":;" in sps101 or "a:" not in sps101 or "f:" not in sps101:
      print("Invalid input for SPS101 letter grade sequence.")
    else:
      al102b = input("Please enter the AL102 letter grade equivalents: ") 
      al102 = al102b.lower()
      if ";:" in al102 or ":;" in al102 or "a:" not in al102:
        print("Invalid input for AL102 letter grade sequence.")
      else:
        notesb = input("Please enter your SPS101 and AL102 letter grades: ")
        notes = notesb.lower()
        if notes.count(",") == 2 or "," not in notes:
          print("Invalid input for SPS101 and AL102 letter grades.")
        elif notes.count(",") == 1:
          splitloc = notes.find(",")
          spsnote = notes[0:splitloc] + ":"
          alnote = notes[splitloc+1:len(notes)+1] + ":"
          if spsnote == "-:":
            spsnote = "c:"
          if len(alnote) == 2 and "-:" in alnote:
            alnote = "c:"
          if len(spsnote) == 2 and "-:" in spsnote:
            spsnote = "c:"
          if spsnote not in sps101:
            print("Your SPS101 letter grade couldn't be found in point-scale.")
          if spsnote in sps101 and alnote not in al102:
            print("Your AL102 letter grade couldn't be found in point-scale.")
          if alnote in al102 and spsnote in sps101:
            spsnoteloc = sps101.find(spsnote)
            scsps = sps101.find(";",spsnoteloc)
            alnoteloc = al102.find(alnote)
            scal = al102.find(";",alnoteloc)
            spsnotenum = (sps101[spsnoteloc+2:scsps])
            alnotenum = (al102[alnoteloc+2:scal])
            gpa = input("Please enter your current GPA: ")
            if ":" in alnotenum:
              alnotenum = alnotenum.replace(":","",1)
            if ":" in spsnotenum:
              spsnotenum = spsnotenum.replace(":","",1)
            if float(gpa)<0 or float(gpa)>4:
              print("Your GPA needs to be in between 0-4.")
            elif 0<float(gpa)<2.2:
              print("Your GPA needs to be at least 2.2.")
            else:
              erasmusscore = float(spsnotenum)/5 + float(alnotenum)*3/10 + float(gpa)*12.5            
              print("Your final Erasmus score is, ",erasmusscore,".",sep = '')